call acmlexample.bat acmlinfo
call acmlexample.bat cfft1d_example
call acmlexample.bat dgetrf_example
call acmlexample.bat drandinitializeuser_example
call acmlexample.bat drandskipleap_example
call acmlexample.bat dranduniform_example
call acmlexample.bat dzfft1d_example
call acmlexample.bat dzfft2d_example
call acmlexample.bat dzfft3d_example
call acmlexample.bat dzfft_example
call acmlexample.bat sgetrf_example
call acmlexample.bat zfft1d_example
call acmlexample.bat zfft1dx_example
call acmlexample.bat zfft1mx_example
call acmlexample.bat zfft2dx_example
call acmlexample.bat zfft3dx_example
call acmlexample.bat cdotu_c_example
call acmlexample.bat cfft1d_c_example
call acmlexample.bat cgels_c_example
call acmlexample.bat cgesv_c_example
call acmlexample.bat dgesdd_c_example
call acmlexample.bat drandinitializeuser_c_example
call acmlexample.bat drandskipleap_c_example
call acmlexample.bat dranduniform_c_example
call acmlexample.bat dzfft1d_c_example
call acmlexample.bat dzfft_c_example
call acmlexample.bat sgels_c_example
call acmlexample.bat sgesv_c_example
call acmlexample.bat sgetrf_c_example
call acmlexample.bat zfft1d_c_example
call acmlexample.bat zgels_c_example
call acmlexample.bat sgetrf_cpp_example
